# Generated by Django 2.0.7 on 2018-07-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180723_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='artist_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/uploads', verbose_name='image'),
        ),
    ]
