# Generated by Django 2.0.7 on 2018-07-23 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180723_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Artist'),
            preserve_default=False,
        ),
    ]
