# Generated by Django 2.0.7 on 2018-07-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180723_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Timestamp',
        ),
        migrations.AddField(
            model_name='album',
            name='notes',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='release',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='track_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
