# Generated by Django 2.0.7 on 2018-07-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
