# Generated by Django 2.0.7 on 2018-07-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180723_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='album',
        ),
    ]
