# Generated by Django 2.0.7 on 2018-07-24 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180724_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='app.Album'),
        ),
    ]
