# Generated by Django 2.0.7 on 2018-07-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180724_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release',
        ),
    ]
