# Generated by Django 2.0.7 on 2018-07-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180727_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='default.png', upload_to='media/'),
        ),
    ]
